/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tools.finemovingmousecursor;

import java.awt.Robot;
import java.awt.MouseInfo;
import java.awt.PointerInfo;
import java.awt.Point;

public class App {
    public static void main(String[] args) {

        int delay = DEFAULT_DELAY;

        if (args.length>=1) {
            try {
                delay = Integer.parseInt(args[0]) * 1000;
            } catch (NumberFormatException nfex) {
            }
        }

        App.fineMove(delay);
    }

    private static final int DEFAULT_DELAY = 3*60*1000;

    public static void fineMove(int delay) {

        System.out.println("Delay time : " + (delay/1000) + " sec.");

        try {

            Robot robot = new Robot();
            robot.setAutoDelay(100);

            while (true) {
                System.out.println("Move!");

                PointerInfo pointerInfo;

                pointerInfo = MouseInfo.getPointerInfo();
                Point point = pointerInfo.getLocation();

                Thread.sleep(100);

                pointerInfo = MouseInfo.getPointerInfo();
                Point point2 = pointerInfo.getLocation();

                // 100ms‚ÌŠÔ‚Éƒ}ƒEƒX‚ª“®‚¢‚Ä‚¢‚È‚©‚Á‚½‚ç“®‚©‚·
                if (point.x == point2.x && point.y == point2.y) {

                    point = pointerInfo.getLocation();
                    robot.mouseMove(point.x-1, point.y);

                    point = pointerInfo.getLocation();
                    robot.mouseMove(point.x+1, point.y);

                    point = pointerInfo.getLocation();
                    robot.mouseMove(point.x, point.y-1);

                    point = pointerInfo.getLocation();
                    robot.mouseMove(point.x, point.y+1);
                }

                Thread.sleep(delay);
            }
        } catch(Exception e) {
            e.printStackTrace();
        }

    }
}
