package tools.hashtool;

import org.apache.commons.codec.digest.DigestUtils;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        if (args.length!=1) {
            System.err.println("Usage: java tools.hashtool.App [source text]");
            return ;
        }

        String source = args[0];
        String hexString = DigestUtils.md5Hex(source); 
        System.out.println(source + "," + hexString);
    }
}
