/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tools.dbcomparator.ui;

/**
 *
 * @author k_watanabe
 */
public class CompareResultFrame extends javax.swing.JFrame {

    /**
     * Creates new form CompareResultFrame
     */
    public CompareResultFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        autoRollCheckBox = new javax.swing.JCheckBox();
        delayTimeTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        scrollCheckBox = new javax.swing.JCheckBox();
        compareTabbedPane = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        compareResultTable = new javax.swing.JTable();
        loadingProgressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        autoRollCheckBox.setText("Auto roll");
        jPanel1.add(autoRollCheckBox);

        delayTimeTextField.setText("300");
        delayTimeTextField.setPreferredSize(new java.awt.Dimension(100, 19));
        jPanel1.add(delayTimeTextField);

        jLabel1.setText("ms");
        jPanel1.add(jLabel1);

        scrollCheckBox.setText("Scroll");
        jPanel1.add(scrollCheckBox);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        compareTabbedPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        compareResultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(compareResultTable);

        compareTabbedPane.addTab("tab1", jScrollPane1);

        getContentPane().add(compareTabbedPane, java.awt.BorderLayout.CENTER);
        getContentPane().add(loadingProgressBar, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompareResultFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompareResultFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompareResultFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompareResultFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CompareResultFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JCheckBox autoRollCheckBox;
    protected javax.swing.JTable compareResultTable;
    protected javax.swing.JTabbedPane compareTabbedPane;
    protected javax.swing.JTextField delayTimeTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JProgressBar loadingProgressBar;
    protected javax.swing.JCheckBox scrollCheckBox;
    // End of variables declaration//GEN-END:variables
}
